### ISSUE TITLE
VX1 Authentication Problem via USB connection

### ISSUE THREAD

**Issue by TokyoTimo** [plathome/docs#1]
I can not login to the system via USB connection. Authentification problem. I am using “root” as login and password, also I tried to use a password which I saved on WEB UI, but all the time “Login incorrect”. Is it possible that this board has some additional users?
Can we set up the board to the default setting?

**Comment by daizoom** [comment]
In case you login via serial console, default root password is 0BSI0T.
Could you please check "7-5. Setting the Root Password" on "Web UI Setup Guide" and try it again?
