### ISSUE TITLE
BLE / mac address is 00:00:00:00:00:00 problem

### ISSUE THREAD

**Issue by TokyoTimo** [plathome/docs#3]
I have activated BLE to work with beacons, but as you can see below that the mac address is 0. Can you please help with it?

 
```
hciconfig -a

hci0:   Type: BR/EDR  Bus: USB

        BD Address: 00:00:00:00:00:00  ACL MTU: 0:0  SCO MTU: 0:0

        DOWN

        RX bytes:504 acl:0 sco:0 events:71 errors:0

        TX bytes:17714 acl:0 sco:0 commands:72 errors:0

        Features: 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00

        Packet type: DM1 DH1 HV1

        Link policy:

        Link mode: SLAVE ACCEPT
```

**Comment by daizoom** [comment]
I am sorry, but I do not know why this problem occurs.
Could you tell me the following?
1. How did you get this information? on Web UI or you executed command?
2. In your information, hci0 is down. Could you confirm hci0 is up and try to scan?

**Comment by Vladyslav93** [comment]
@daizoom Thanks for your question. I check this information via WEB UI and also with the command "hciconfig -a". Also, tried to up the system but I got an error message that has not the device for it. And scan doesn#t working.

But I found the solution, I have disconnect Bluetooth module and connect back, then need to reboot the board. After this operation, BLE has MAC address and I can scan.

One additional question:

On the WEB UI, When I am trying to detect a ble beacon, I have next message: "And for data collection tool is enabled, it does not allow the detection of BLE device." Do you know what it can be? I have activated all.

Thanks.

**Comment by daizoom** [comment]
@Vladyslav93 I guess Data Acquisition is enable.
Could you check Data Acquisition is "Do not use" on [Service] -> [Basic] tab and try again?

**Comment by Vladyslav93** [comment]
@daizoom Thanks. Yes, it works. I thought that I need to activate BLE in "Basic" Tab, but... I was wrong.
